apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: app-config.school59-ekb.ru  # Домен для app-config
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-config-service
            port:
              number: 5000
  - host: flask-app.school59-ekb.ru    # Домен для flask-app-pr1
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-app-pr1-service
            port:
              number: 5000