apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: test-deploy
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: test.k8s.school59-ekb.ru
    http:
      paths:
      - path: /app-config
        pathType: Prefix
        backend:
          service:
            name: app-config
            port:
              number: 5000
      - path: /flask-app-pr1
        pathType: Prefix
        backend:
          service:
            name: flask-app-pr1
            port:
              number: 5000