apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2  # Важно для корректного перенаправления
spec:
  rules:
  - host: app-config.school59-ekb.ru  # Единый домен
    http:
      paths:
      - path: /config(/|$)(.*)  # Путь /config
        pathType: Prefix
        backend:
          service:
            name: app-config-service
            port:
              number: 5000
      - path: /flask(/|$)(.*)   # Путь /flask
        pathType: Prefix
        backend:
          service:
            name: flask-app-pr1-service
            port:
              number: 5000